server:
  port: 2020
spring:
  application:
    name: zull_getway
  security:
    user:
      name: name
      password: password
eureka:
  client:
    service-url:
      defaultZone: http://name:password@127.0.0.1:8761/eureka/

zuul:
  routes:
